### ISSUE TITLE
软件没有mysql数据库选项

### ISSUE THREAD

**Issue by XingHuoLiaoYuanBaby** [Ryze-T/Sylas#1]
刚下载完最新版，发现没有mysql的选项
![QQ截图20220217114402](https://user-images.githubusercontent.com/50256400/154401096-8d95be08-b441-4fd1-b910-c3423ea1570d.png)

**Comment by Ryze-T** [comment]
开发初期是想写的，在实际开发过程中发现现在对mysql getshell的方法都不够通用，受限太多，所以暂时先不写，等到我找到好的合适的组合利用的方法我会加上去，如果大家有好的方法也欢迎给我tips

**Comment by XingHuoLiaoYuanBaby** [comment]
确实，对于mysql我也没找到比较好的利用工具，之前发现sql server有一款工具是SQL TOOLS 2.0功能增强版，非常实用

**Comment by XingHuoLiaoYuanBaby** [comment]
> 开发初期是想写的，在实际开发过程中发现现在对mysql getshell的方法都不够通用，受限太多，所以暂时先不写，等到我找到好的合适的组合利用的方法我会加上去，如果大家有好的方法也欢迎给我tips

确实，对于mysql我也没找到比较好的利用工具，之前发现sql server有一款工具是SQL TOOLS 2.0功能增强版，非常实用

**Comment by timetravel-boy** [comment]
可以参考利群的
