### ISSUE TITLE
报毒？

### ISSUE THREAD

**Issue by ohnoa** [Ryze-T/Sylas#4]
怎么报毒了？
<img width="666" alt="image" src="https://user-images.githubusercontent.com/29808559/160069582-6685c374-4d8d-4b62-96f3-968ca3710c68.png">

**Comment by Ryze-T** [comment]
首先明确一点就是并不存在病毒
看样子应该是火绒报毒的，报的是 C# 相关的，如果担心可以在虚拟机里使用
